version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8880:80"
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - "8881:8881"
    networks:
        - app-network
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
networks:
  app-network:
    driver: bridge      